// flow-typed signature: dc9aef1cf62330f1815b5c81c4dd72b0
// flow-typed version: <<STUB>>/react-toasts_v^2.0.13/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-toasts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-toasts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-toasts/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-toasts/build/index' {
  declare module.exports: $Exports<'react-toasts/build'>;
}
declare module 'react-toasts/build/index.js' {
  declare module.exports: $Exports<'react-toasts/build'>;
}
