// flow-typed signature: 44afc23bb7441283a6ddf612ffa582de
// flow-typed version: <<STUB>>/yarn_v^1.9.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yarn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yarn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yarn/bin/yarn' {
  declare module.exports: any;
}

declare module 'yarn/lib/cli' {
  declare module.exports: any;
}

declare module 'yarn/lib/v8-compile-cache' {
  declare module.exports: any;
}

declare module 'yarn/preinstall' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yarn/bin/yarn.js' {
  declare module.exports: $Exports<'yarn/bin/yarn'>;
}
declare module 'yarn/lib/cli.js' {
  declare module.exports: $Exports<'yarn/lib/cli'>;
}
declare module 'yarn/lib/v8-compile-cache.js' {
  declare module.exports: $Exports<'yarn/lib/v8-compile-cache'>;
}
declare module 'yarn/preinstall.js' {
  declare module.exports: $Exports<'yarn/preinstall'>;
}
